"use client";
import { useEffect,useRef,useState } from "react";
import type { Schedule } from "@/hooks/useWorkshopSchedule";
import { workshopConfig as c } from "@/lib/workshopConfig";
import { useAnalytics } from "@/hooks/useAnalytics";
export function PurchaseModal({schedule,onClose,lang="en"}:{schedule:Schedule;onClose:()=>void;lang?:"en"|"ur"}){
 const ur=lang==="ur";
 const [step,setStep]=useState(1);const [method,setMethod]=useState("Bank Transfer");const [busy,setBusy]=useState(false);const [error,setError]=useState("");const modal=useRef<HTMLDivElement>(null);const {track}=useAnalytics();
 useEffect(()=>{document.body.style.overflow="hidden";const key=(e:KeyboardEvent)=>{if(e.key==="Escape")onClose();if(e.key==="Tab"){const els=modal.current?.querySelectorAll<HTMLElement>("button,input,select");if(!els?.length)return;const first=els[0],last=els[els.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};addEventListener("keydown",key);modal.current?.querySelector<HTMLElement>("button")?.focus();return()=>{document.body.style.overflow="";removeEventListener("keydown",key)}},[onClose]);
 const details=method==="Bank Transfer"?`${c.paymentDetails.bankName} • ${c.paymentDetails.accountTitle} • ${c.paymentDetails.accountNumber}`:method==="Easypaisa"?c.paymentDetails.easypaisaNumber:c.paymentDetails.jazzcashNumber;
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");track("registration_submitted");try{const body=new FormData(e.currentTarget);body.set("paymentMethod",method);body.set("batchDate",schedule.batchDateString);body.set("offerVersion",c.offerVersion);const r=await fetch("/api/register",{method:"POST",body});const data=await r.json() as {ok?:boolean;error?:string};if(!r.ok)throw new Error(data.error||"Submission failed");track("registration_success");setStep(3)}catch(err){setError(err instanceof Error?err.message:"Dobara try karein");track("registration_error")}finally{setBusy(false)}}
 return <div className="overlay" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="modal" role="dialog" aria-modal="true" aria-labelledby="purchase-title" ref={modal}><button className="close" aria-label="Close" onClick={onClose}>×</button>{step<3&&<><h2 id="purchase-title">{ur?"اپنی ورکشاپ سیٹ لاک کریں":"Lock Your Workshop Seat"}</h2><p className="muted">{schedule.batchDateDisplay} • 8:00 PM PKT</p><div className="steps"><span className="on"/><span className={step>=2?"on":""}/><span/></div></>}
 {step===1&&<><h3>1. Payment Method Select Karein</h3><div className="methods">{["Bank Transfer","Easypaisa","JazzCash"].map(x=><button key={x} className={`method ${method===x?"selected":""}`} onClick={()=>{setMethod(x);track("payment_method_selected",{method:x})}}>{x}</button>)}</div><div className="details"><b>{method} Details</b><p>{details}</p><button className="method" onClick={()=>{navigator.clipboard.writeText(details);track("bank_details_copied")}}>Copy details</button></div><button className="btn full" onClick={()=>{setStep(2);track("form_started")}}>Payment Ho Gayi — Details Submit Karein →</button></>}
 {step===2&&<form onSubmit={submit}><div className="field"><label>Full Name</label><input name="fullName" required minLength={2} autoComplete="name"/></div><div className="field"><label>WhatsApp Number</label><input name="phone" required inputMode="tel" placeholder="+92 3XX XXXXXXX" autoComplete="tel"/></div><div className="field"><label>Email Address</label><input name="email" type="email" required autoComplete="email"/></div><div className="field"><label>Transaction ID</label><input name="transactionId" required minLength={4}/></div><div className="field"><label>Payment Screenshot (JPG, PNG or WebP — max 5MB)</label><input name="paymentProof" type="file" required accept="image/jpeg,image/png,image/webp" capture="environment" onChange={()=>track("payment_proof_uploaded")}/></div><input type="hidden" name="batchDate" value={schedule.batchDateString}/>{error&&<p className="error">{error}</p>}<button className="btn full" disabled={busy}>{busy?"Submit ho raha hai…":"Registration Submit Karein →"}</button></form>}
 {step===3&&<div className="success"><div className="check">✅</div><h2>{ur?"رجسٹریشن موصول ہو گئی!":"Registration received!"}</h2><p>{ur?"ادائیگی کی تصدیق کے بعد ورکشاپ کا لنک واٹس ایپ پر بھیجا جائے گا۔":"After payment verification, the workshop link will be sent on WhatsApp."}</p><button className="btn" onClick={onClose}>{ur?"مکمل":"Done"}</button></div>}</div></div>
}
